# Generated by Django 4.1.2 on 2022-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='ProjectsModel',
        ),
    ]
