# Generated by Django 4.1.2 on 2022-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_projects_projectsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='screensort_switch',
            field=models.BooleanField(default=False),
        ),
    ]
